codecov:
  # Coverage target: ≥70% conform PRD
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  # Global coverage targets
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

  # Frontend-specific settings
  flags:
    frontend:
      paths:
        - frontend/src/
      target: 70%
      threshold: 2%
    backend:
      paths:
        - backend/src/
      target: 70% 
      threshold: 2%

# Comment configuration for PR feedback
comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  hide_project_coverage: false
  
  # Custom message template
  template: |
    ## 📊 Code Coverage Report
    
    Coverage: **{{ coverage }}%** {{ coverage_diff }}
    
    ### Coverage by Area:
    {{ files_coverage_table }}
    
    ### Summary
    - **Target**: 70% minimum (PRD requirement)
    - **Current**: {{ coverage }}%
    - **Status**: {{ status }}
    
    {{ files_missing_coverage }}

# Ignore files that don't need coverage
ignore:
  - "frontend/src/**/*.test.ts"
  - "frontend/src/**/*.test.tsx"
  - "frontend/src/**/*.spec.ts"
  - "frontend/src/**/*.spec.tsx"
  - "frontend/src/**/*.d.ts"
  - "frontend/src/test/"
  - "frontend/tests/"
  - "frontend/src/mocks/"
  - "frontend/src/shared-constants/" # Generated files
  - "backend/src/**/*.spec.ts"
  - "backend/src/**/*.test.ts"
  - "backend/test/"
  - "scripts/"
  - "*.config.js"
  - "*.config.ts" 